--Create tables
CREATE TABLE UserData(
userID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_UserDataID PRIMARY KEY,
pass VARCHAR(20) NOT NULL,
userFullName VARCHAR(80) NOT NULL,
email VARCHAR(80) NOT NULL,
registerDate DATETIME NOT NULL CONSTRAINT DF_RegisterDate DEFAULT (getDate()),
userAddress VARCHAR(100) NULL,
phoneNumber INT NULL,
department VARCHAR(20) NULL,
userType VARCHAR(20) NOT NULL CONSTRAINT DF_UserType DEFAULT ('User')
);

CREATE TABLE Products(
productID INT IDENTITY(100, 1) NOT NULL CONSTRAINT PK_ProductID PRIMARY KEY,
productName VARCHAR(50) NOT NULL CONSTRAINT DF_ProductName DEFAULT ('Product Unnamed'),
quantity INT NOT NULL CONSTRAINT DF_ProductsQuantity DEFAULT (0)
);

CREATE TABLE OrdersDetail(
orderID INT NOT NULL CONSTRAINT PK_OrderID PRIMARY KEY,
productID INT NOT NULL CONSTRAINT FK_OrderDetail_ProductID FOREIGN KEY REFERENCES dbo.Products (productID),
quantity INT NOT NULL CONSTRAINT DF_OrderDetail_Quantity DEFAULT (1),
shippingAddress VARCHAR(100) NOT NULL,
orderDate DATETIME NOT NULL CONSTRAINT DF_OrdersDetail_Date DEFAULT (getDate()),
amount MONEY NOT NULL
);

CREATE TABLE Orders(
orderID INT NOT NULL CONSTRAINT FK_OrderID FOREIGN KEY REFERENCES dbo.OrdersDetail (orderID),
productID INT NOT NULL CONSTRAINT FK_Orders_ProductID FOREIGN KEY REFERENCES dbo.Products (productID),
amount MONEY NOT NULL,
orderDate DATETIME NOT NULL CONSTRAINT DF_Orders_Date DEFAULT (getDate())
);

CREATE TABLE Teams(
teamID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_TeamID PRIMARY KEY,
teamName VARCHAR(20) NOT NULL,
creationDate DATETIME NOT NULL,
country VARCHAR(30) NOT NULL,
city VARCHAR(30) NOT NULL
);

CREATE TABLE Players(
playerID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_PlayerID PRIMARY KEY,
playerName VARCHAR(80) NOT NULL,
bornDate DATETIME NOT NULL,
shots INT NOT NULL CONSTRAINT DF_PlayerShots DEFAULT (0),
goals INT NOT NULL CONSTRAINT DF_PlayerGoals DEFAULT (0),
height FLOAT NOT NULL,
weight FLOAT NOT NULL,
speed FLOAT NULL,
teamID INT NOT NULL CONSTRAINT FK_TeamID FOREIGN KEY REFERENCES dbo.Teams (teamID),
nationality VARCHAR(30) NULL
);

CREATE TABLE Stadiums(
stadiumID INT IDENTITY(1, 1) NOT NULL CONSTRAINT PK_StadiumID PRIMARY KEY,
stadiumName VARCHAR(40) NOT NULL,
capacity INT NOT NULL,
openDate DATETIME NOT NULL,
country VARCHAR(30) NOT NULL,
city VARCHAR(30) NOT NULL
);

--Create Procedures